// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcokgfmrxonlbtebtadh.supabase.co"; //JAG
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjb2tnZm1yeG9ubGJ0ZWJ0YWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NjY1MTksImV4cCI6MjA3MTI0MjUxOX0.sVa575UTz5A1fLKQ89xaDdR83mPSBI8kJVARcYwAktM"

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});